[build]
  functions = "netlify/functions"
  command = "echo 'Netlify build complete'" # Basit bir komut

[[headers]]
  for = "/netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*" # Fonksiyonlara eri≈üime izin ver